---
- name: Install PHP  and ther useful modules
  apt: name={{ item }} state=installed update_cache=yes
  notify: "restart web services"
  with_items:
    - php
    - libapache2-mod-php
    - php-curl
    - php-gd
    - php-mysql
    - php-opcache
    - php-zip
    - php-xsl
    - php-xml
    - php-mcrypt
    - php-json
    - php-intl
    - php-mbstring
    - php-soap

- name: Configure PHP
  ini_file:
    dest: /etc/php/7.0/apache2/php.ini
    section: PHP
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
    - { option: 'upload_max_filesize', value: "20M"}
    - { option: 'memory_limit',        value: "256M"}
    - { option: 'max_execution_time',  value: "360"}
    - { option: 'max_input_vars',      value: "1000"}
    - { option: 'post_max_size',      value: "8M"}
  notify: restart apache
