---
- name: Set SSH secure configuration
  template: src=sshd_config.j2 dest=/etc/ssh/sshd_config
  tags: sshd
  notify: restart sshd

- name: Install UFW (firewall)
  apt: name=ufw state=present

- ufw:
    rule: allow
    name: OpenSSH
    state: enabled
