---
- name: stop postfix
  shell: postfix stop

- name: restart postfix
  shell: postfix reload
  listen: "restart mail services"

- name: restart dovecot
  service: name=dovecot state=restarted
  listen: "restart mail services"
